/*
 * BSD 3-Clause License
 * 
 * Copyright (c) 2016-2022, Adam Berlinger
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifdef __cplusplus
    extern "C" {
#endif

/* sin_table/table_.h files are
    generated by tools/gen_sin.m file */

#if SAMPLE_TABLE_SIZE == 64
    #include "sin_tables/table64.h"
    #define SAMPLE_TABLE_SIZE_BITS  (6)
#elif SAMPLE_TABLE_SIZE == 128
    #include "sin_tables/table128.h"
    #define SAMPLE_TABLE_SIZE_BITS  (7)
#elif SAMPLE_TABLE_SIZE == 256
    #include "sin_tables/table256.h"
    #define SAMPLE_TABLE_SIZE_BITS  (8)
#elif SAMPLE_TABLE_SIZE == 512
    #include "sin_tables/table512.h"
    #define SAMPLE_TABLE_SIZE_BITS  (9)
#elif SAMPLE_TABLE_SIZE == 1024
    #include "sin_tables/table1024.h"
    #define SAMPLE_TABLE_SIZE_BITS  (10)
#elif SAMPLE_TABLE_SIZE == 2048
    #include "sin_tables/table2048.h"
    #define SAMPLE_TABLE_SIZE_BITS  (11)
#elif SAMPLE_TABLE_SIZE == 4096
    #include "sin_tables/table4096.h"
    #define SAMPLE_TABLE_SIZE_BITS  (12)
#else
    #error "Unknown table size"
#endif

/* Document the include tree */
#if DOXYGEN
    #include "sin_tables/table64.h"
    #include "sin_tables/table128.h"
    #include "sin_tables/table256.h"
    #include "sin_tables/table512.h"
    #include "sin_tables/table1024.h"
    #include "sin_tables/table2048.h"
    #include "sin_tables/table4096.h"
#endif

#ifdef __cplusplus
    }
#endif
